// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpV1eaTXSzXfW7KKGPzdb5nRFjOn_NhIg',
    appId: '1:28072428818:web:883247fce838c0a9d65fcb',
    messagingSenderId: '28072428818',
    projectId: 'artstepacademy',
    authDomain: 'artstepacademy.firebaseapp.com',
    storageBucket: 'artstepacademy.firebasestorage.app',
    measurementId: 'G-W5BL3CTZZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBkj-Trg2PjaQeIUFwyMv5Gnw4Pj1-DQ',
    appId: '1:28072428818:android:0cdc53f90b7a717dd65fcb',
    messagingSenderId: '28072428818',
    projectId: 'artstepacademy',
    storageBucket: 'artstepacademy.firebasestorage.app',
    androidClientId: '28072428818-dandsjg697vnhp5brm5mr7m4mn664s3d.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvf2O7d6DZ2gP2AjyKrcFTvmXBAPi9p4',
    appId: '1:28072428818:ios:5efb128286da6885d65fcb',
    messagingSenderId: '28072428818',
    projectId: 'artstepacademy',
    storageBucket: 'artstepacademy.firebasestorage.app',
    iosClientId: '28072428818-jmeekg05b3sktpilihpsdv3umeesforp.apps.googleusercontent.com',
    iosBundleId: 'com.example.artworkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApvf2O7d6DZ2gP2AjyKrcFTvmXBAPi9p4',
    appId: '1:28072428818:ios:5efb128286da6885d65fcb',
    messagingSenderId: '28072428818',
    projectId: 'artstepacademy',
    storageBucket: 'artstepacademy.firebasestorage.app',
    iosClientId: '28072428818-jmeekg05b3sktpilihpsdv3umeesforp.apps.googleusercontent.com',
    iosBundleId: 'com.example.artworkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpV1eaTXSzXfW7KKGPzdb5nRFjOn_NhIg',
    appId: '1:28072428818:web:a51b41b5ba9de106d65fcb',
    messagingSenderId: '28072428818',
    projectId: 'artstepacademy',
    authDomain: 'artstepacademy.firebaseapp.com',
    storageBucket: 'artstepacademy.firebasestorage.app',
    measurementId: 'G-CE7QHFLE06',
  );
}
